apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: labwordpress
  labels:
    app: wordpress
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: wordpress
  clusterIP: None
  