apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: labwordpress
  labels:
    app: wordpress
spec:
  accessModes:
    -  ReadWriteOnce
  resources:
    requests:
      storage: 3Gi 